# Test we can logon to 'webservers' and execute python with json lib.
# ansible-playbook configure-delta-printers.yml --diff
# options:  --limit deltamaker-0306.local --check
---
- name: Configure delta printers first run
  gather_facts: false
  hosts: all
  tasks:
    - name: Create vudocustom directory
      ansible.builtin.file:
        path: /home/pi/.octoprint/uploads/vudocustom
        owner: pi
        group: pi
        state: directory
      register: create_octoprint_directory

    - name: Enable some user alias
      ansible.builtin.blockinfile:
        path: /home/pi/.bashrc
        insertafter: '^# some more ls aliases'
        block: |
          alias ll='ls -lart --color=auto'
          alias vim='vi'

    - name: Turn off wifi power management
      ansible.builtin.lineinfile:
        path: /etc/rc.local
        state: present
        insertbefore: '^exit 0'
        line: /sbin/iwconfig wlan0 power off
      become: true
      notify: Restart pi

    - name: Fix ssh freezing issues on /etc/ssh/sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: IPQoS cs0 cs0
      become: true
      notify: Restart pi

    - name: Update authorized_key
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', './vudocustom_id_rsa.pub') }}"

    - name: Update octoprint users.yaml with template
      ansible.builtin.template:
       src: templates/octoprint_users_yaml.j2
       dest: /home/pi/.octoprint/users.yaml
      notify: Restart octoprint

    - name: Update octoprint config.yaml with template
      ansible.builtin.template:
       src: templates/octoprint_config_yaml.j2
       dest: /home/pi/.octoprint/config.yaml
      notify: Restart octoprint

    - name: Update deltamaker boot delta.txt configuration
      ansible.builtin.template:
       src: templates/boot_deltamaker_txt.j2
       dest: /boot/deltamaker.txt
      become: true
      notify: Restart pi

    - name: Update deltamaker boot config.txt configuration
      ansible.builtin.template:
       src: templates/boot_config_txt.j2
       dest: /boot/config.txt
      become: true
      notify: Restart pi

  handlers:
    - name: Restart pi
      ansible.builtin.reboot:
        msg: "Rebooting machine now"
      become: true

    - name: Restart octoprint
      ansible.builtin.service:
        name: octoprint
        state: restarted
      become: true
