# Test we can logon to 'webservers' and execute python with json lib.
# ansible-playbook configure-delta-printers.yml --diff
# options:  --limit deltamaker-0306.local --check
---
- name: Configure delta printers first run
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Stop octoprint service
      ansible.builtin.service:
        name: octoprint
        state: stopped
      become: true

    - name: Create vudocustom directory
      ansible.builtin.file:
        path: /home/pi/.octoprint/uploads/vudocustom
        owner: pi
        group: pi
        state: directory

    - name: Turn off bluetooth on boot
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        insertafter: '^# Uncomment some or all of these to enable the optional hardware interfaces'
        line: dtparam=disable-bt
      become: true

    - name: Enable some user alias
      ansible.builtin.blockinfile:
        path: /home/pi/.bashrc
        insertafter: '^# some more ls aliases'
        block: |
          alias ll='ls -lart --color=auto'
          alias vim='vi'

    - name: Turn off wifi power management
      ansible.builtin.lineinfile:
        path: /etc/rc.local
        state: present
        insertbefore: '^exit 0'
        line: /sbin/iwconfig wlan0 power off
      become: true

    - name: Fix ssh freezing issues on /etc/ssh/sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: IPQoS cs0 cs0
      become: true

    - name: reboot machines
      ansible.builtin.reboot:
        msg: "Rebooting machine now"
      become: true
