# ansible-playbook upgrade-printer-software.yml --limit deltamaker-0306.local --diff --check
# options:  --limit deltamaker-0306.local --check
#Steps:
# 1- Incremental steps to update
# Debian Jessie --> Stretch --> Buster --> Bullseye --> Bookworm
#
#
#
#

---
- name: Configure delta printers first run
  hosts: all
  tasks:
    - name: Backup specific files for each 3D printers

    - name: Update repo for archival debian jessie support
      ansible.builtin.template:
        src: ./templates/sources.list
        dest: /etc/apt/sources.list
      become: true

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true
      ignore_errors: yes

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        upgrade: yes
        update_cahce: yes
        cache_valid_time: 86400
        force: true
        install_recommends: true
      become: true.